---
- shell: |
    oc -n production patch dc/vektor --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/command", "value": ["sh", "-c", "sleep infinity"]}]'
    oc -n production scale --replicas=1 dc/vektor
